config/routes.rb
ActionController::Routing::Routes.draw do |map|

  

  map.root :controller => "main", :action => "index"
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :words
  belongs_to :user
  validates_length_of :name, :minimum => 1

  named_scope :all_public, {conditions: ['is_private = ?', false]}
  
  def create_word(args)
    words.create(args)
  end

  def move_word_to(word, deck)
    raise "The word #{word.id} does't belong to the deck #{id}" unless word.deck_id == id
    word.destroy
    deck.words.create(word.attributes)
  end

  def fresh_copy
    Deck.new(attributes.merge(is_active: true, is_private: true))
  end

  def similar_words(str)
    word = OaldParser::WordExtractor.new.extract(str)
    words.find(:all, conditions: ['word LIKE ?', "%#{word}%"])
  end

  def random_word
    w = words.show_by_now
    return nil if w.empty?
    w[rand(w.size)]
  end
  
  def random(n)
    n = words.size if n > words.size
    words.shuffle[0...n]
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_filter :logging_required, :retrive_decks

  def list
    @deck = Deck.new
  end

  def show
    @deck = current_user.find_deck(params[:id].to_i)
    if !@deck
      flash[:error] = 'There is no deck with such ID'
      redirect_to(controller: 'main', action: 'index')
    end
    @other_decks = current_user.decks - [@deck]
  end

  def create
    @deck = current_user.create_deck(params[:deck])
    if @deck.save
      redirect_to(controller: 'decks', action: 'show', id: @deck.id)
    else
      render(action: 'list')
    end
  end

  def edit
    @deck = current_user.find_deck(params[:id].to_i)
    if @deck
      if @deck.update_attributes(params[:deck])
        redirect_to(controller: 'decks', action: 'show', id: @deck.id)
      else
        render(template: 'decks/show')
      end
    else
      redirect_to(controller: 'main', action: 'index')
      flash[:error] = 'There is no deck with such ID'
    end
  end

  def delete
    deck = current_user.find_deck(params[:id].to_i)
    current_user.delete_deck(deck)
    flash[:message] = "Your deck '#{deck.name}' is successfully deleted"
    redirect_to(controller: 'decks', action: 'list')
  end

  private
  def retrive_decks
    @decks = current_user.decks(true)
  end
end

app/helpers/decks_helper.rb
module DecksHelper
  def repeat_date_output(date)
    if Time.zone.now > date
      "repeat right now"
    else
      "repeat in #{distance_of_time_in_words_to_now(date)}"
    end
  end
end

app/views/decks/_word.html.erb
<div class="word<%= is_even ? 'Even' : 'Odd' %>">
  <%= check_box_tag 'word_ids[]', word.id, false, class: 'word_checkbox' %>
  <%= popup_window word.word, 'Edit Word',
                   url_for(action: "edit", controller: 'words', id: word.id) %>

  <span class="wordStatus">(<%= repeat_date_output(word.show_at) %>)</span>
  <span class="smallLink">
  <%= link_to 'Delete', {controller: 'words', action: 'delete', id: word.id}, {confirm: 'Are you sure?'} %>
  </span>
</div>

app/views/decks/list.html.erb
<script type="text/javascript">
    function showAll() {
        $$('.deckDescription').each(function(e) {
            e.show();
        });
    }

    function showActive() {
        $$('.deckDescription').each(function(e) {
            if(e.getAttribute('active') == 'true'){
                e.show();
            }else{
                e.hide();
            }
        });
    }

    function showInactive() {
        $$('.deckDescription').each(function(e) {
            if(e.getAttribute('active') == 'true'){
                e.hide();
            }else{
                e.show();
            }
        });
    }

    document.observe('dom:loaded', function() {
        $('allDecks').observe('click', showAll);
        $('activeDecks').observe('click', showActive);
        $('inactiveDecks').observe('click', showInactive);
    });
</script>

<h2>Create a New Deck</h2>
<%= error_messages_for 'deck' %>
<fieldset>
  <legend>Fill in Form</legend>
  <% form_for :deck, :url => {:action => 'create'} do |form| %>
      <div class="formBlock">
        <label for="deck_name">Name</label>
        <%= form.text_field :name, :size => 40 %>
      </div>

      <div class="formBlock">
        <label for="deck_is_private">Private</label>
        <%= form.check_box :is_private %>
      </div>

      <div class="formBlock"><%= submit_tag 'Create New Deck', :class => "submit" %></div>
  <% end %>
</fieldset>
Or Just <%= link_to 'Use Public Decks', controller: 'share', action: 'list_public_decks' %>

<h2>Your Decks
  <div id="deckFilter">
      <a href="#" id="allDecks">All</a>
      <a href="#" id="activeDecks">Active</a>
      <a href="#" id="inactiveDecks">Inactive</a>
  </div>                       
</h2>

<% if !@decks.empty? %>
    <% for deck in @decks do %>
        <div class="deckDescription" active="<%= deck.is_active %>">
          <h3><%= link_to deck.name, :controller => 'decks', :action => 'show', :id => deck.id %></h3>

          <p><%= deck.is_private ? 'Private' : 'Public' %></p>

          <p>There are <%= deck.words.size %> words</p>

          <p><%= deck.words.show_by_now.size %> should be repeated</p>
          <h4><%= link_to 'Learn Words', :controller => 'learn', :action => 'show_word', :deck_id => deck.id %></h4>
        </div>
    <% end %>
<% else %>
    You have no decks
<% end %>

app/views/decks/show.html.erb
<script type="text/javascript">
  function selectAllCheckboxes(){
    $$('.word_checkbox').each(function(e){ e.checked = 1});
  }

  function deleteSelected(){
    if(confirm('Are you sure?')){
      var ids = $$('.word_checkbox').findAll(function(e){ return e.checked == 1})
      .collect(function(e){return 'id[]=' + e.value});
      var url = '<%=url_for(action: "delete_all", controller: 'words')%>' + '?' + ids.join('&');
      document.location.href = url;
    }
  }

  function moveSelected(){
    if(confirm('Are you sure?')){
      var ids = $$('.word_checkbox').findAll(function(e){ return e.checked == 1})
      .collect(function(e){return 'id[]=' + e.value});
      var selected = $$('#otherDecks option').find(function(ele){return !!ele.selected});
      var url = '<%=url_for(action: "move_all", controller: 'words')%>' + '?' + ids.join('&')
        + "&dest_deck_id=" + selected.value + "&src_deck_id=" + <%= @deck.id %>;
      document.location.href = url;
    }
  }

  function initOtherDecks(){
    var otherDecks = <%= ! @other_decks.empty?  %>;
    if(otherDecks){
      var options = "<%=  @other_decks.collect{|d| "<option value='#{d.id}'>#{d.name}</option>"}.join('') %>";
      $("otherDecks").update(options);
    }else{
      $("otherDecks").hide();
      $("moveSelectedLink").hide();
    }
  }

  document.observe('dom:loaded' , function() {
    initOtherDecks();
    $('selectAllLink').observe('click', selectAllCheckboxes);
    $('deleteSelectedLink').observe('click', deleteSelected);
    $('moveSelectedLink').observe('click', moveSelected);
  });
</script>

<fieldset>
  <legend>Edit Deck <strong>'<%= @deck.name %>'</strong></legend>
  <%= error_messages_for 'deck' %>
  <% form_for :deck, url: {action: 'edit', id: @deck.id} do |form| %>
    <div class="formBlock">
      <label for="deck_name">Name</label>
      <%= form.text_field :name, :size => 40 %>
    </div>

    <div class="formBlock">
      <label for="deck_is_private">Private</label>
      <%= form.check_box :is_private %>
    </div>

    <div class="formBlock">
      <label for="deck_is_active">Active</label>
      <%= form.check_box :is_active %>
    </div>

    <div class="formBlock">
      <%= submit_tag 'Save Changes', class: "submit" %>
        <%= link_to 'Delete', {controller: 'decks', action: 'delete', id: @deck.id}, {confirm: 'Are you sure?'} %>
      </div>
    <% end %>
  </fieldset>

  <div class="button">
    <%= popup_window 'Create a New Word', 'Create a Word',
      url_for(action: "create", controller: 'words', deck_id: @deck.id) %>
  </div>

  <div class="button">
    <%= link_to 'Learn Words', :controller => 'learn', :action => 'show_word', :deck_id => @deck.id %>
  </div>
  <div style="clear:both;"></div>

  <% if @deck.words.empty? %>

    <h2>The deck is empty</h2>

  <% else %>

    <div id="deckStats">
      The are <%= @deck.words.size %> words in this deck. There are <%= @deck.words.learnt.size %> learnt words.
    </div>

    <div id="deckActions">
      <span><a href="#" id="selectAllLink">Select All</a></span>
      <span><a href="#" id="deleteSelectedLink"> Delete Selected</a></span>
      <span><a href="#" id="moveSelectedLink"> Move Selected To </a>
      <select id="otherDecks"></select></span>
    </div>

    <% for word in @deck.words %>
      <% is_even = is_even ? false : true %>
      <%= render partial: 'word', locals: {word: word, is_even: is_even} %>
    <% end %>
  <% end %>